# Generated by Django 5.0.6 on 2024-06-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='bio',
        ),
        migrations.AddField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
