# Generated by Django 5.0.6 on 2024-06-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sent/'),
        ),
    ]
